version: '2'
services:
    tdqtcas-app:
        image: tdqtcas
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=tdqtcas-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    tdqtcas-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: tdqtcas-cassandra
    tdqtcas-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=tdqtcas-cassandra
    tdqtcas-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: tdqtcas-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
